// js/database.js

// Banco de Dados Completo do Fallout 4
const dbProdutos = [
    // --- CURA & QUÍMICOS (AID) ---
    { id: 1, nome: 'Stimpak', preco: 48, categoria: 'Cura' },
    { id: 2, nome: 'RadAway', preco: 80, categoria: 'Cura' },
    { id: 3, nome: 'Rad-X', preco: 40, categoria: 'Cura' },
    { id: 4, nome: 'Bolsa de Sangue', preco: 20, categoria: 'Cura' },
    { id: 5, nome: 'Addictol', preco: 125, categoria: 'Cura' },
    { id: 6, nome: 'Antibióticos', preco: 75, categoria: 'Cura' },
    { id: 7, nome: 'Jet', preco: 50, categoria: 'Químico' },
    { id: 8, nome: 'Psycho', preco: 50, categoria: 'Químico' },
    { id: 9, nome: 'Mentats', preco: 50, categoria: 'Químico' },
    { id: 10, nome: 'Buffout', preco: 45, categoria: 'Químico' },
    { id: 11, nome: 'Med-X', preco: 50, categoria: 'Químico' },
    { id: 12, nome: 'Stealth Boy', preco: 400, categoria: 'Ajuda' },
    { id: 13, nome: 'Mentats de Uva', preco: 65, categoria: 'Químico' },
    { id: 14, nome: 'X-Cell', preco: 160, categoria: 'Químico' },

    // --- COMIDA & BEBIDA (FOOD) ---
    { id: 15, nome: 'Nuka-Cola', preco: 20, categoria: 'Bebida' },
    { id: 16, nome: 'Nuka-Cola Quantum', preco: 50, categoria: 'Bebida' },
    { id: 17, nome: 'Nuka-Cherry', preco: 40, categoria: 'Bebida' },
    { id: 18, nome: 'Vim!', preco: 30, categoria: 'Bebida' },
    { id: 19, nome: 'Água Purificada', preco: 20, categoria: 'Bebida' },
    { id: 20, nome: 'Água Suja', preco: 5, categoria: 'Bebida' },
    { id: 21, nome: 'Cerveja Gwinnett', preco: 8, categoria: 'Bebida' },
    { id: 22, nome: 'Whisky', preco: 15, categoria: 'Bebida' },
    { id: 23, nome: 'Carne de Radstag', preco: 45, categoria: 'Comida' },
    { id: 24, nome: 'Bife de Deathclaw', preco: 110, categoria: 'Comida' },
    { id: 25, nome: 'Ovo de Mirelurk', preco: 15, categoria: 'Comida' },
    { id: 26, nome: 'Carne de Yao Guai', preco: 65, categoria: 'Comida' },
    { id: 27, nome: 'BlamCo Mac & Cheese', preco: 12, categoria: 'Comida' },
    { id: 28, nome: 'Cram', preco: 25, categoria: 'Comida' },
    { id: 29, nome: 'Dandy Boy Apples', preco: 14, categoria: 'Comida' },
    { id: 30, nome: 'Fancy Lads Snack Cakes', preco: 16, categoria: 'Comida' },
    { id: 31, nome: 'InstaMash', preco: 12, categoria: 'Comida' },
    { id: 32, nome: 'Pork n Beans', preco: 12, categoria: 'Comida' },
    { id: 33, nome: 'Salisbury Steak', preco: 20, categoria: 'Comida' },
    { id: 34, nome: 'Sugar Bombs', preco: 14, categoria: 'Comida' },
    { id: 35, nome: 'Yum Yum Deviled Eggs', preco: 18, categoria: 'Comida' },

    // --- ARMAS (WEAPONS) ---
    { id: 36, nome: 'Pistola 10mm', preco: 50, categoria: 'Arma' },
    { id: 37, nome: 'Pistola .44', preco: 95, categoria: 'Arma' },
    { id: 38, nome: 'Rifle de Caça', preco: 55, categoria: 'Arma' },
    { id: 39, nome: 'Escopeta de Combate', preco: 145, categoria: 'Arma' },
    { id: 40, nome: 'Rifle de Combate', preco: 117, categoria: 'Arma' },
    { id: 41, nome: 'Submetralhadora', preco: 109, categoria: 'Arma' },
    { id: 42, nome: 'Rifle de Assalto', preco: 144, categoria: 'Arma' },
    { id: 43, nome: 'Minigun', preco: 382, categoria: 'Arma' },
    { id: 44, nome: 'Fat Man', preco: 512, categoria: 'Arma' },
    { id: 45, nome: 'Lança-Mísseis', preco: 314, categoria: 'Arma' },
    { id: 46, nome: 'Rifle Laser', preco: 68, categoria: 'Arma' },
    { id: 47, nome: 'Rifle de Plasma', preco: 123, categoria: 'Arma' },
    { id: 48, nome: 'Mosquete Laser', preco: 44, categoria: 'Arma' },
    { id: 49, nome: 'Rifle Gauss', preco: 228, categoria: 'Arma' },
    { id: 50, nome: 'Alien Blaster', preco: 1551, categoria: 'Arma' },
    { id: 51, nome: 'Cryolator', preco: 302, categoria: 'Arma' },
    { id: 52, nome: 'Shishkebab', preco: 200, categoria: 'Arma' },
    { id: 53, nome: 'Super Sledge', preco: 180, categoria: 'Arma' },
    { id: 54, nome: 'Power Fist', preco: 100, categoria: 'Arma' },
    { id: 55, nome: 'Junk Jet', preco: 285, categoria: 'Arma' },
    { id: 56, nome: 'Railway Rifle', preco: 290, categoria: 'Arma' },

    // --- MUNIÇÃO (AMMO) ---
    { id: 57, nome: 'Munição .38', preco: 1, categoria: 'Munição' },
    { id: 58, nome: 'Munição 10mm', preco: 2, categoria: 'Munição' },
    { id: 59, nome: 'Munição .45', preco: 3, categoria: 'Munição' },
    { id: 60, nome: 'Munição 5.56mm', preco: 2, categoria: 'Munição' },
    { id: 61, nome: 'Célula de Fusão', preco: 3, categoria: 'Munição' },
    { id: 62, nome: 'Núcleo de Fusão', preco: 162, categoria: 'Munição' },
    { id: 63, nome: 'Cartucho de Plasma', preco: 4, categoria: 'Munição' },
    { id: 64, nome: 'Mini Nuke', preco: 100, categoria: 'Munição' },
    { id: 65, nome: 'Míssil', preco: 25, categoria: 'Munição' },
    { id: 66, nome: 'Cartucho .308', preco: 3, categoria: 'Munição' },
    { id: 67, nome: 'Cartucho de Shotgun', preco: 3, categoria: 'Munição' },
    { id: 68, nome: 'Fuel de Lança-Chamas', preco: 1, categoria: 'Munição' },

    // --- TRAJES & ARMADURAS (APPAREL) ---
    { id: 69, nome: 'Traje do Vault 111', preco: 20, categoria: 'Traje' },
    { id: 70, nome: 'Pip-Boy 3000 Mk IV', preco: 0, categoria: 'Traje' },
    { id: 71, nome: 'Armadura de Couro', preco: 25, categoria: 'Armadura' },
    { id: 72, nome: 'Armadura de Metal', preco: 45, categoria: 'Armadura' },
    { id: 73, nome: 'Armadura de Combate', preco: 110, categoria: 'Armadura' },
    { id: 74, nome: 'Armadura Synth', preco: 85, categoria: 'Armadura' },
    { id: 75, nome: 'Capacete do Exército', preco: 15, categoria: 'Traje' },
    { id: 76, nome: 'Traje Hazmat', preco: 85, categoria: 'Traje' },
    { id: 77, nome: 'Vestido de Lantejoulas', preco: 16, categoria: 'Traje' },
    { id: 78, nome: 'Smoking', preco: 18, categoria: 'Traje' },
    { id: 79, nome: 'Óculos Escuros', preco: 6, categoria: 'Traje' },
    { id: 80, nome: 'Bandana', preco: 3, categoria: 'Traje' },
    { id: 81, nome: 'Capacete T-60b', preco: 140, categoria: 'Armadura' },
    { id: 82, nome: 'Peitoral X-01', preco: 320, categoria: 'Armadura' },

    // --- SUCATA & LIXO (JUNK) ---
    { id: 83, nome: 'Ventilador de Mesa', preco: 4, categoria: 'Lixo' },
    { id: 84, nome: 'Máquina de Escrever', preco: 8, categoria: 'Lixo' },
    { id: 85, nome: 'Cola Maravilha', preco: 6, categoria: 'Lixo' },
    { id: 86, nome: 'Duct Tape', preco: 4, categoria: 'Lixo' },
    { id: 87, nome: 'Microscópio', preco: 25, categoria: 'Lixo' },
    { id: 88, nome: 'Scanner Biométrico', preco: 18, categoria: 'Lixo' },
    { id: 89, nome: 'Câmera Fotográfica', preco: 12, categoria: 'Lixo' },
    { id: 90, nome: 'Relógio de Ouro', preco: 40, categoria: 'Lixo' },
    { id: 91, nome: 'Ursinho de Pelúcia', preco: 3, categoria: 'Lixo' },
    { id: 92, nome: 'Carrinho de Brinquedo', preco: 8, categoria: 'Lixo' },
    { id: 93, nome: 'Chave Inglesa', preco: 3, categoria: 'Lixo' },
    { id: 94, nome: 'Martelo', preco: 3, categoria: 'Lixo' },
    { id: 95, nome: 'Parafusos (Caixa)', preco: 8, categoria: 'Lixo' },
    { id: 96, nome: 'Engrenagens', preco: 6, categoria: 'Lixo' },
    { id: 97, nome: 'Mola', preco: 5, categoria: 'Lixo' },
    { id: 98, nome: 'Circuito Militar', preco: 35, categoria: 'Lixo' },
    { id: 99, nome: 'Sensor de Módulo', preco: 22, categoria: 'Lixo' },
    { id: 100, nome: 'Globo Terrestre', preco: 10, categoria: 'Lixo' }
];